version: "3.7"
services: 
    #Project
    site2:
        build: 
            args: 
                user: site2   #Will be used in Dockerfile
                uid: 1000               #Will be used in Dockerfile
            context: ./
            dockerfile: Dockerfile
        image: site2
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - site2

    #nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: site2-nginx
        # environment:
        #     VIRTUAL_PORT: ${APP_PORT}
        #     VIRTUAL_HOST: site2.colmeiatecnologia.com.br
        #     LETSENCRYPT_HOST: site2.colmeiatecnologia.com.br
        #     LETSENCRYPT_EMAIL: administracao@colmeiatecnologia.com.br
        ports:
            - ${APP_PORT}:80
#            - ${SSL_PORT}:443
        expose:
           - ${APP_PORT}
#            - ${SSL_PORT}
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d
        networks:
            - site2
            - proxy

    #mysql
    #comment if using AWS RDS
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - ${FORWARD_DB_PORT}:3306
        volumes:
            - ./.docker/mysql/db_data:/var/lib/mysql
        networks:
            - site2
    
networks:
    site2:
        driver: bridge
    proxy:
        driver: bridge
        external: true
