version: "3.7"
services: 
    #nginx
    nginx-proxy:
        image: nginx:alpine
        restart: unless-stopped
        build: 
            context: ./
            dockerfile: Dockerfile
        ports:
             - 80:80
            #  - 443:443
        volumes:
            # - ./:/var/www
            - ./docker/nginx/config:/etc/nginx/conf.d
            - ./docker/nginx/html:/var/www/html
            # - ./certs:/
        networks:
            - proxy
    #nginx
    # letsencrypt:
    #     build: 
    #         context: ./
    #         dockerfile: Dockerfile
    #     volumes:
    #         - ./docker/nginx/config:/etc/nginx/conf.d
    #     networks:
    #         - proxy
    #     depends_on:
    #         - nginx-proxy
    
networks:
    proxy:
        driver: bridge
        external: true
