# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8000:80'
#            - '80:8001'
#            - '${HMR_PORT:-8080}:8080'
        expose:
            - 8000
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            VIRTUAL_HOST: site3.colmeiatecnologia.com.br
            LETSENCRYPT_HOST: site3.colmeiatecnologia.com.br
            LETSENCRYPT_EMAIL: administracao@colmeiatecnologia.com.br
            VIRTUAL_PORT: 8000
        volumes:
            - '.:/var/www/html'
#        networks:
#            - sail
#            - nginx-proxy
        network_mode: bridge
#        depends_on:
#            - mysql
#    mysql:
#        image: 'mysql/mysql-server:8.0'
#        ports:
#            - '${FORWARD_DB_PORT:-3306}:3306'
#        environment:
 #           MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
 #           MYSQL_ROOT_HOST: "%"
#            MYSQL_DATABASE: '${DB_DATABASE}'
#            MYSQL_USER: '${DB_USERNAME}'
#            MYSQL_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_ALLOW_EMPTY_PASSWORD: 1
#        volumes:
#            - 'sail-mysql:/var/lib/mysql'
#            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
#        networks:
#            - sail
#        network_mode: bridge
#        healthcheck:
#            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
#            retries: 3
#            timeout: 5s
#networks:
#    sail:
#        driver: bridge
#    nginx-proxy:
#        external: true 
#        driver: bridge
#networks:
#  default:
#    external:
#      name: nginx-proxy
volumes:
    sail-mysql:
        driver: local
