version: "3.7"
services: 
    #nginx
    nginx-proxy:
        image: ubuntu/nginx
        restart: unless-stopped
        build: 
            context: ./
            dockerfile: Dockerfile
        entrypoint: ["bash", "-c", "
            certbot --nginx -n --redirect --agree-to 
            -d beawebartisan.com 
            -d site9.beawebartisan.com 
            -d site10.beawebartisan.com 
            -m hi@rogeriopereira.dev
            && certbot renew --dry-run
        "]
        ports:
             - 80:80
             - 443:443
        volumes:
            - ./docker/nginx/config:/etc/nginx/conf.d
            - certs:/etc/letsencrypt
        networks:
            - proxy
    
networks:
    proxy:
        driver: bridge
        external: true
volumes:
    certs: