version: "3.7"
services: 
    #nginx
    nginx-proxy:
        image: nginx:alpine
        restart: unless-stopped
        ports:
             - 80:80
             - 443:443
        volumes:
            # - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d
            # - ./docker/nginx/:/etc/nginx/sites-enabled
            # - ./certs:/